# Generated by Django 4.1.7 on 2023-04-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300, unique=True)),
                ('password', models.CharField(max_length=300, unique=True)),
                ('password2', models.CharField(max_length=300, unique=True)),
                ('email', models.CharField(max_length=300, unique=True)),
                ('first_name', models.CharField(max_length=300, unique=True)),
                ('last_name', models.CharField(max_length=300, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
